version: "3.9"
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: treefam-rest
    restart: always
    ports:
      - "7000:4000"
    environment:
      FLASK_APP: "app/main"
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "4000"
      FLASK_ENV: "development"
    volumes:
      - .:/usr/src/treefam-api:rw
    links:
      - mongodb
    networks: 
        treefam_network:
          aliases:
            - treefam_host

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root1234
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
        treefam_network:
          aliases:
            - mongodb_host

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root1234
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    networks:
        treefam_network:
          aliases:
            - mongoexp_host
    depends_on:
      - mongodb
    
#volumes:
#  schemas: {}

networks:
  treefam_network:
    name: treefam_net
    driver: bridge
    ipam: 
      driver: default